Repository K1rL3s/aliceio, pull requests merged in 2025-01, with the labels that each got.

#21 Поддержка рантайм контекста облачных яндекс функций
  aliceio/webhook/yandex_functions/__init__.py
  aliceio/webhook/yandex_functions/base.py
  aliceio/webhook/yandex_functions/context.py
  aliceio/webhook/yandex_functions/one_skill.py
  docs/tutorial/connect-yandex-functions.md
  examples/yandex_functions.py
  tests/test_webhook/test_yandex_functions.py
Labels: enhancement

#23 Убрал неправильные ClassVar аннотации
  aliceio/types/alice_event.py
  aliceio/types/error_event.py
  aliceio/types/message.py
  aliceio/types/quota.py
  aliceio/types/session.py
  aliceio/types/update.py
  aliceio/types/uploaded_image.py
  aliceio/types/uploaded_sound.py
  aliceio/webhook/aiohttp_server/base.py
Labels: enhancement

#24 Тесты на prepare_value
  aliceio/utils/funcs.py
  aliceio/webhook/aiohttp_server/base.py
  tests/test_api/test_client/test_session/test_base_session.py
Labels: enhancement

#29 Добавил новую функцию get_value в fsm
  aliceio/fsm/context.py
  aliceio/fsm/storage/base.py
  aliceio/fsm/storage/memory.py
  tests/test_fsm/storage/test_storages.py
  tests/test_fsm/test_context.py
Labels: enhancement

#33 Обновление pydantic в pyproject.toml
  pyproject.toml
Labels: enhancement

#34 Обновление aiohttp в pyproject.toml
  pyproject.toml
Labels: enhancement

#32 Добавление документации к FSMStrategy
  aliceio/fsm/strategy.py
Labels: documentation

#31 Поправил и проверил ссылки в README.md
  README.md
  docs/tutorial/middlewares.md
Labels: bug, documentation
